export { App, type AppLayout } from "./App";
export { useAppContext, AppProvider, type AppHost, type VaultSource, type OllamaEnsureRunningResult } from "./context";
export { Documents } from "./views/Documents";
export { ProfileView } from "./views/Profile";
export { Conflicts } from "./views/Conflicts";
export { FactsGraph } from "./views/FactsGraph";
export { SettingsView } from "./views/Settings";
export { Onboarding } from "./views/Onboarding";
export { SpotlightOverlay } from "./views/SpotlightOverlay";
export { FloatingShortcut } from "./views/FloatingShortcut";
export { SensitivityGate, MaskedValue } from "./components/SensitivityGate";
export { ThemeProvider, useTheme, type Theme } from "./components/theme";
export { BRAND, tx, status } from "./lib/brand";
export { OctoMark, OctoLockup } from "./components/octo-mark";
